import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { UpdateUserDto } from './dto/update-user.dto';
import { CreateUserDto } from './dto/create-user.dto';
import * as bcrypt from 'bcryptjs';
import { Role } from '@prisma/client';
import { MailService } from '@/mail/mail.service';
import { ForgotPasswordDto } from './dto/forgot-password.dto';

@Injectable()
export class UsersService {
  constructor(private prisma: PrismaService, private mailService: MailService) { }

  async findAll() {
    return this.prisma.user.findMany({
      where: { isActive: true },
      select: {
        id: true,
        email: true,
        firstName: true,
        lastName: true,
        role: true,
        isActive: true,
        teamId: true,
        departmentId: true,
        createdAt: true,
      },
    });
  }

  async findOne(id: string) {
    const user = await this.prisma.user.findUnique({
      where: { id },
      select: {
        id: true,
        email: true,
        firstName: true,
        lastName: true,
        role: true,
        isActive: true,
        teamId: true,
        departmentId: true,
        createdAt: true,
        updatedAt: true,
      },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    return user;
  }

  async create(createUserDto: CreateUserDto) {
    const { email, firstName, lastName, isAutoGeneratedPassword } = createUserDto;
    const normalizedEmail = email?.trim().toLowerCase();
    if (!normalizedEmail || !firstName || !lastName) {
      throw new BadRequestException('email, firstName and lastName are required');
    }

    const existingUser = await this.prisma.user.findUnique({
      where: { email: normalizedEmail },
      select: { id: true },
    });

    if (existingUser) {
      throw new BadRequestException('User with this email already exists');
    }

    // Normalize role: fallback to MEMBER
    let role: Role = Role.MEMBER;
    if (createUserDto.role) {
      role = createUserDto.role;
    }

    // Hash password (generate if not provided - though frontend typically provides one)
    const passwordToHash =
      createUserDto.password && createUserDto.password.length >= 6
        ? createUserDto.password
        : Math.random().toString(36).slice(-12);
    const hashedPassword = await bcrypt.hash(passwordToHash, 10);

    const user = await this.prisma.user.create({
      data: {
        email: normalizedEmail,
        password: hashedPassword,
        firstName: createUserDto.firstName,
        lastName: createUserDto.lastName,
        role,
        isActive: createUserDto.isActive ?? true,
        teamId: createUserDto.teamId || null,
        departmentId: createUserDto.departmentId || null,
      },
      select: {
        id: true,
        email: true,
        firstName: true,
        lastName: true,
        role: true,
        isActive: true,
        teamId: true,
        departmentId: true,
        createdAt: true,
        updatedAt: true,
      },
    });

    if (isAutoGeneratedPassword) {
      await this.mailService.sendEmailThroughProvider(
        { email: user.email, name: `${user.firstName} ${user.lastName}` },
        {
          subject: 'Your Account Has Been Created',
          html: `<p>Dear ${user.firstName},</p>
                 <p>Your account has been created. Here are your login details:</p>
                 <ul>
                   <li>Email: ${user.email}</li>
                   <li>Temporary Password: ${passwordToHash}</li>
                 </ul>
                 <p>Please log in and change your password.</p>
                 <p>Best regards,<br/>The Team</p>
                 </ul>`,
          text: `Dear ${user.firstName},\n\nYour account has been created. Here are your login details:\n\nEmail: ${user.email}\nTemporary Password: ${passwordToHash}\n\nPlease log in and change your password.\n\nBest regards,\nThe Team`,
        },
        { metadata: { cc: [] } },
      );
    }

    return user;
  }

  async update(id: string, updateUserDto: UpdateUserDto) {
    const user = await this.prisma.user.update({
      where: { id },
      data: updateUserDto,
      select: {
        id: true,
        email: true,
        firstName: true,
        lastName: true,
        role: true,
        isActive: true,
        teamId: true,
        departmentId: true,
        updatedAt: true,
      },
    });

    return user;
  }

  async getCurrentUserRole(userId: string) {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: { role: true },
    });

    return user?.role || 'MEMBER';
  }

  async initiatePasswordForgot(forgotPasswordDto: ForgotPasswordDto) {
    const { email, oldPassword, newPassword } = forgotPasswordDto;
    const normalizedEmail = email?.trim().toLowerCase();

    if (!normalizedEmail || !oldPassword || !newPassword) {
      throw new BadRequestException('Email, old password, and new password are required');
    }

    const user = await this.prisma.user.findUnique({
      where: { email: normalizedEmail },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    const isOldPasswordValid = await bcrypt.compare(oldPassword, user.password);
    if (!isOldPasswordValid) {
      throw new BadRequestException('Old password is incorrect');
    }

    const hashedNewPassword = await bcrypt.hash(newPassword, 10);

    await this.prisma.user.update({
      where: { email: normalizedEmail },
      data: { password: hashedNewPassword },
    });

    return { message: 'Password updated successfully' };
  }

  async initiatePasswordReset(email: string) {
    const normalizedEmail = email?.trim().toLowerCase();

    if (!normalizedEmail) {
      throw new BadRequestException('Email is required');
    }

    const user = await this.prisma.user.findUnique({
      where: { email: normalizedEmail },
    });

    if (!user) {
      throw new NotFoundException('User not found');
    }

    const tempPassword = Math.random().toString(36).slice(-12);
    const hashedTempPassword = await bcrypt.hash(tempPassword, 10);
    await this.prisma.user.update({
      where: { email: normalizedEmail },
      data: { password: hashedTempPassword },
    });

    await this.mailService.sendEmailThroughProvider(
      { email: user.email, name: `${user.firstName} ${user.lastName}` },
      {
        subject: 'Password Reset Request',
        html: `<p>Dear ${user.firstName},</p>
               <p>Your password has been reset. Here is your temporary password:</p>
                <ul>
                  <li>Temporary Password: ${tempPassword}</li>
                </ul>
                <p>Please log in and change your password.</p>
                <p>Best regards,<br/>The Team</p>`,
        text: `Dear ${user.firstName},\n\nYour password has been reset. Here is your temporary password:\n\nTemporary Password: ${tempPassword}\n\nPlease log in and change your password.\n\nBest regards,\nThe Team`,
      },
      { metadata: { cc: [] } },
    );
    return { message: 'Temporary password has been sent to your email' };
  }
}
